create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 name text not null default 'NOVIA User',
 username text not null unique,
 bio text default '',
 avatar_url text,
 created_at timestamptz not null default now()
);
create table if not exists public.conversations (id bigint generated by default as identity primary key, created_at timestamptz not null default now());
create table if not exists public.conversation_members (conversation_id bigint references public.conversations(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, primary key(conversation_id,user_id));
create table if not exists public.messages (id bigint generated by default as identity primary key, conversation_id bigint references public.conversations(id) on delete cascade, sender_id uuid references auth.users(id) on delete cascade, text text not null default '', gift jsonb, created_at timestamptz not null default now());
create index if not exists profiles_username_idx on public.profiles(lower(username));
create index if not exists messages_conversation_idx on public.messages(conversation_id,created_at);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select using (true);
drop policy if exists "own profile insert" on public.profiles;
create policy "own profile insert" on public.profiles for insert with check (auth.uid()=id);
drop policy if exists "own profile update" on public.profiles;
create policy "own profile update" on public.profiles for update using (auth.uid()=id);
drop policy if exists "members read conversations" on public.conversations;
create policy "members read conversations" on public.conversations for select using (exists(select 1 from public.conversation_members cm where cm.conversation_id=id and cm.user_id=auth.uid()));
drop policy if exists "members read membership" on public.conversation_members;
create policy "members read membership" on public.conversation_members for select using (user_id=auth.uid() or exists(select 1 from public.conversation_members cm where cm.conversation_id=conversation_id and cm.user_id=auth.uid()));
drop policy if exists "members read messages" on public.messages;
create policy "members read messages" on public.messages for select using (exists(select 1 from public.conversation_members cm where cm.conversation_id=conversation_id and cm.user_id=auth.uid()));
drop policy if exists "members send messages" on public.messages;
create policy "members send messages" on public.messages for insert with check (sender_id=auth.uid() and exists(select 1 from public.conversation_members cm where cm.conversation_id=conversation_id and cm.user_id=auth.uid()));

create or replace function public.get_or_create_direct_conversation(target_user_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare existing_id bigint; new_id bigint;
begin
 if auth.uid() is null then raise exception 'Not authenticated'; end if;
 if target_user_id = auth.uid() then raise exception 'Cannot chat with yourself'; end if;
 select c.id into existing_id
 from conversations c
 join conversation_members a on a.conversation_id=c.id and a.user_id=auth.uid()
 join conversation_members b on b.conversation_id=c.id and b.user_id=target_user_id
 where (select count(*) from conversation_members x where x.conversation_id=c.id)=2
 limit 1;
 if existing_id is not null then return existing_id; end if;
 insert into conversations default values returning id into new_id;
 insert into conversation_members(conversation_id,user_id) values(new_id,auth.uid()),(new_id,target_user_id);
 return new_id;
end;$$;
revoke all on function public.get_or_create_direct_conversation(uuid) from public;
grant execute on function public.get_or_create_direct_conversation(uuid) to authenticated;

-- Realtime: add messages to the publication if it is not already present.
do $$ begin
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then
   alter publication supabase_realtime add table public.messages;
 end if;
exception when undefined_object then null; end $$;
